version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 10
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt install -y nodejs
      - echo Checking Node Vesion
      - node -v
      - echo Checking NPM Version
      - npm -v
  pre_build:
    commands:
      - echo Installing dependencies
      - cd client
      - npm install
  build:
    commands:
      - echo building
      - cd client
      - npm run build
artifacts:
  files: 
    - "**/*"
  discard-paths: no
  base-directory: client/dist
